
RELEASEDIR=../../release
LIBDIR=../../lib

LICENSE=$(LIBDIR)/license.js
LEARNER_CLASS=$(LIBDIR)/learner-class.js
SYNTHETICKEYBOARD_CLASS=$(LIBDIR)/synthetickeyboard.js
RANDOM_CLASS=$(LIBDIR)/random.js

